version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd examples/eks-cluster-with-new-vpc
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd examples/eks-cluster-with-new-vpc
            terraform apply -target="module.vpc"  -auto-approve tfapply
            terraform apply -target="module.eks_blueprints"   -auto-approve tfapply 
            terraform apply -target="module.eks_blueprints_kubernetes_addons"  -auto-approve tfapply 
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            cd examples/eks-cluster-with-new-vpc
#            terraform destroy -target="module.vpc"  -auto-approve tfdestroy
#            terraform destroy -target="module.eks_blueprints"   -auto-approve tfdestroy
#            terraform destroy -target="module.eks_blueprints_kubernetes_addons"  -auto-approve tfdestroy 
            terraform plan -destroy -out tfdestroy  
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            cd examples/eks-cluster-with-new-vpc
           # terraform apply -auto-approve tfdestroy
            terraform apply -target="module.vpc"  -auto-approve tfdestroy
            terraform apply -target="module.eks_blueprints"   -auto-approve tfdestroy
            terraform apply -target="module.eks_blueprints_kubernetes_addons"  -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
